"""initial schema

Revision ID: 5eb2bd19a21b
Revises: 
Create Date: 2025-10-13 23:55:36.348888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eb2bd19a21b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('origen_lat', sa.Float(), nullable=False),
    sa.Column('origen_lng', sa.Float(), nullable=False),
    sa.Column('destino_lat', sa.Float(), nullable=False),
    sa.Column('destino_lng', sa.Float(), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hecorp_schema'
    )
    op.create_index(op.f('ix_hecorp_schema_rutas_created_at'), 'rutas', ['created_at'], unique=False, schema='hecorp_schema')
    op.create_index(op.f('ix_hecorp_schema_rutas_id'), 'rutas', ['id'], unique=False, schema='hecorp_schema')
    op.create_index(op.f('ix_hecorp_schema_rutas_updated_at'), 'rutas', ['updated_at'], unique=False, schema='hecorp_schema')
    op.create_index(op.f('ix_hecorp_schema_rutas_user_id'), 'rutas', ['user_id'], unique=False, schema='hecorp_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hecorp_schema_rutas_user_id'), table_name='rutas', schema='hecorp_schema')
    op.drop_index(op.f('ix_hecorp_schema_rutas_updated_at'), table_name='rutas', schema='hecorp_schema')
    op.drop_index(op.f('ix_hecorp_schema_rutas_id'), table_name='rutas', schema='hecorp_schema')
    op.drop_index(op.f('ix_hecorp_schema_rutas_created_at'), table_name='rutas', schema='hecorp_schema')
    op.drop_table('rutas', schema='hecorp_schema')
    # ### end Alembic commands ###
